### ISSUE TITLE
New Laser Temperature Measurement Sensor

### ISSUE THREAD

**Issue by acbuynak** [OSU-AIMS/coaliron_16ton_support#5]
Issue tracking to add software support for new sensor installed on equipment. Model: `optct3MH1SF`

<img src="https://www.optris.com/tl_files/bilder/products/kompaktserie/ct-1m-2m/ir-thermometer-optris-ct-1m-2m-with-box.jpg" width="400" />

**Comment by hansen95** [comment]
Wired analog output to 0-20mA input #3 on the P1-08ADL-1 module. 
Set low temp alarm to 400 C and kept default high temp alarm at 600 C.  
Wired low temp alarm relay output to digital input #3 on the P1-15CDD2 module.
Current behavior is that alarm output is OFF when sensed temp > 400 C. This corresponds to a Normally Closed alarm behavior.  May want to change this to N.O.  so that a positive signal is required before pressing (i.e., part > 400 C). 
Tested using a soldering iron set to 850 C; able to see temperature on LCD display (read ~ 405 C) and state change on PLC input. Did not check 0-20mA signal. 
Need to:
1. check calibration
2. write Arduino test script to read 0-20 mA input and scale to deg. C. 
3. integrate test script with rest of code
4. add ROS publishers for alarm states and actual temperature
